AD-15708: Script to set the autoAssociateIDPUser on all organizations in on-prem instance
Bluescape/bluescape-cli-archived-2022 pull request #33
Opened 2023-05-02 15:24 UTC by prem15588

[AD-15708](https://jira.common.bluescape.com/browse/AD-15708)
[AD-15709](https://jira.common.bluescape.com/browse/AD-15709)
We combined both scripts into one and executed them. Added both arguments organizationId/accountId as optional (at least one required) 
1. Check the given organization `autoAssociateIdentityProviderUser` field. If it is not true, then update it's true. Mark all other organization's flags as `false`.
2. If account id is present in the argument then map all the organizations in the instance with that account.

2023-05-03 13:32 UTC, aaditya-bluescape requested changes

2023-05-03 13:32 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision.ts
> +  console.log('siloed user provisioning');
remove the console logs

2023-05-03 13:32 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision/set.ts
> +              await organizationService.updateOrganizationAutoAssociateIDPUser(
instead of using await under loop
please make an array and push all the calls into it and use promise.all after the loop and use await there

2023-05-03 13:32 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision/set.ts
> +      for await (const organization of results) {
I don't think await is needed here

2023-05-03 13:35 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision/set.ts
> +          if (accountId) {
not needed here as it's a mandatory arg

2023-05-10 12:49 UTC, prem15588 commented on src/commands/siloeduserprovision/set.ts
> +          if (accountId) {
So that you know, it is not required. Because we have one command to apply both org IDp and accountId, If I choose organiziation/accountId to update, I can. But at least one param should be passed in the command.

2023-05-10 12:49 UTC, prem15588 commented on src/commands/siloeduserprovision/set.ts
> +      for await (const organization of results) {
It's not needed technically. But eslint purpose I added here.

2023-05-10 12:51 UTC, prem15588 commented on src/commands/siloeduserprovision/set.ts
> +              await organizationService.updateOrganizationAutoAssociateIDPUser(
We want to know the result of each org result log mentioned screenshot, so I decided to asynchronously.

2023-05-10 12:54 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision/set.ts
> +          if (accountId) {
not getting your point 
I meant w already checked above that accounted must be valid and presented then why we need to check with IF condition here

2023-05-10 12:59 UTC, HMageswari approved these changes

2023-05-10 12:59 UTC, aaditya-bluescape commented on src/commands/siloeduserprovision/set.ts
> +          if (accountId) {
Okay resolving it but I am still wondering how an undefined value passes the check being a valid account ID

2023-05-10 13:01 UTC, prem15588 commented on src/commands/siloeduserprovision/set.ts
> +          if (accountId) {
undefined values are not considered in the earlier check

2023-05-10 13:08 UTC, aaditya-bluescape approved these changes

2023-05-10 14:59 UTC, merged